function checkCatch(monster) {
    switch (monster.toLowerCase()) {
        case 'deoxys':
            return 'deoxys-normal';
        case 'wormadam':
            return 'wormadam-plant';
        case 'giratina':
            return 'giratina-altered';
        case 'shaymin':
            return 'shaymin-land';
        case 'basculin':
            return 'basculin-red-striped';
        case 'darmanitan':
            return 'darmanitan-standard';
        case 'tornadus':
            return 'tornadus-incarnate';
        case 'thundurus':
            return 'thundurus-incarnate';
        case 'landorus':
            return 'landorus-incarnate';
        case 'keldeo':
            return 'keldeo-ordinary';
        case 'meloetta':
            return 'meloetta-aria';
        case 'meowstic':
            return 'meowstic-male';
        case 'aegislash':
            return 'aegislash-shield';
        case 'pumpkaboo':
            return 'pumpkaboo-average';
        case 'gourgeist':
            return 'gourgeist-average';
        case 'zygarde':
            return 'zygarde-50';
        case 'oricorio':
            return 'oricorio-baile';
        case 'lycanroc':
            return 'lycanroc-midday';
        case 'wishiwashi':
            return 'wishiwashi-solo';
        case 'minior':
            return 'minior-red-meteor';
        case 'mimikyu':
            return 'mimikyu-disguised';
        case 'toxtricity':
            return 'toxtricity-amped';
        case 'eiscue':
            return 'eiscue-ice';
        case 'indeedee':
            return 'indeedee-male';
        case 'morpeko':
            return 'morpeko-full-belly';
        case 'urshifu':
            return 'urshifu-single-strike';
        case 'basculegion':
            return 'basculegion-male';
        case 'enamorus':
            return 'enamorus-incarnate';
        case 'oinkologne':
            return 'oinkologne-male';
        case 'maushold':
            return 'maushold-family-of-four';
        case 'squawkabilly':
            return 'squawkabilly-green-plumage';
        case 'palafin':
            return 'palafin-zero';
        case 'tatsugiri':
            return 'tatsugiri-curly';
        case 'dudunsparce':
            return 'dudunsparce-two-segment';
        default:
            return monster;
    }
}

function checkEm(monster) {
    switch (monster.toLowerCase()) {
        case 'deoxys-normal':
        case 'deoxys':
            return 'deoxys';
        case 'wormadam-plant':
            return 'wormadam';
        case 'giratina-altered':
            return 'giratina';
        case 'shaymin-land':
            return 'shaymin';
        case 'basculin-red-striped':
            return 'basculin';
        case 'darmanitan-standard':
            return 'darmanitan';
        case 'tornadus-incarnate':
            return 'tornadus';
        case 'thundurus-incarnate':
            return 'thundurus';
        case 'landorus-incarnate':
            return 'landorus';
        case 'keldeo-ordinary':
            return 'keldeo';
        case 'meloetta-aria':
            return 'meloetta';
        case 'meowstic-male':
            return 'meowstic';
        case 'aegislash-shield':
            return 'aegislash';
        case 'pumpkaboo-average':
            return 'pumpkaboo';
        case 'gourgeist-average':
            return 'gourgeist';
        case 'zygarde-50':
            return 'zygarde';
        case 'oricorio-baile':
            return 'oricorio';
        case 'lycanroc-midday':
            return 'lycanroc';
        case 'wishiwashi-solo':
            return 'wishiwashi';
        case 'minior-red-meteor':
            return 'minior';
        case 'mimikyu-disguised':
            return 'mimikyu';
        case 'toxtricity-amped':
            return 'toxtricity';
        case 'eiscue-ice':
            return 'eiscue';
        case 'indeedee-male':
            return 'indeedee';
        case 'morpeko-full-belly':
            return 'morpeko';
        case 'urshifu-single-strike':
            return 'urshifu';
        case 'basculegion-male':
            return 'basculegion';
        case 'enamorus-incarnate':
            return 'enamorus';
        case 'oinkologne-male':
            return 'oinkologne';
        case 'maushold-family-of-four':
            return 'maushold';
        case 'squawkabilly-green-plumage':
            return 'squawkabilly';
        case 'palafin-zero':
            return 'palafin';
        case 'tatsugiri-curly':
            return 'tatsugiri';
        case 'dudunsparce-two-segment':
            return 'dudunsparce';
        default:
            return monster;
    }
}