function checkEm(monster) {
    switch (monster.toLowerCase()) {
        case 'deoxys-normal':
        case 'deoxys':
            return 'deoxys';
        case 'wormadam-plant':
            return 'wormadam';
        case 'giratina-altered':
            return 'giratina';
        case 'shaymin-land':
            return 'shaymin';
        case 'basculin-red-striped':
            return 'basculin';
        case 'darmanitan-standard':
            return 'darmanitan';
        case 'tornadus-incarnate':
            return 'tornadus';
        case 'thundurus-incarnate':
            return 'thundurus';
        case 'landorus-incarnate':
            return 'landorus';
        case 'keldeo-ordinary':
            return 'keldeo';
        case 'meloetta-aria':
            return 'meloetta';
        case 'meowstic-male':
            return 'meowstic';
        case 'aegislash-shield':
            return 'aegislash';
        case 'pumpkaboo-average':
            return 'pumpkaboo';
        case 'gourgeist-average':
            return 'gourgeist';
        case 'zygarde-50':
            return 'zygarde';
        case 'oricorio-baile':
            return 'oricorio';
        case 'lycanroc-midday':
            return 'lycanroc';
        case 'wishiwashi-solo':
            return 'wishiwashi';
        case 'minior-red-meteor':
            return 'minior';
        case 'mimikyu-disguised':
            return 'mimikyu';
        case 'toxtricity-amped':
            return 'toxtricity';
        case 'eiscue-ice':
            return 'eiscue';
        case 'indeedee-male':
            return 'indeedee';
        case 'morpeko-full-belly':
            return 'morpeko';
        case 'urshifu-single-strike':
            return 'urshifu';
        case 'basculegion-male':
            return 'basculegion';
        case 'enamorus-incarnate':
            return 'enamorus';
        case 'oinkologne-male':
            return 'oinkologne';
        case 'maushold-family-of-four':
            return 'maushold';
        case 'squawkabilly-green-plumage':
            return 'squawkabilly';
        case 'palafin-zero':
            return 'palafin';
        case 'tatsugiri-curly':
            return 'tatsugiri';
        case 'dudunsparce-two-segment':
            return 'dudunsparce';
        default:
            return monster;
    }
}